# Generated by Django 5.1.6 on 2025-03-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_recipe_author_recipe_created_recipe_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updated',
        ),
    ]
