# Generated by Django 5.1.6 on 2025-03-10 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_recipe_created_remove_recipe_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='createdOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='updatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
