# Generated by Django 5.1.6 on 2025-03-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='description',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
